Repository CoolDogee/cap-that-pic, pull requests merged in 2019-11, with the labels that each got.

#22 this commit fixes #21
  client/public/uploads/03_Hilarious-Photos-that-Will-Get-You-Through-the-Week_293553839_Kichigin-760x506.jpg
  client/public/uploads/iamcooldogee.png
  client/public/uploads/temp.jpg
  client/public/uploads/test.png
  server.js
Labels: Backend, enhancement

#23 Return 3 lines for caption
  go/server/handler.go
  go/server/server_test.go
Labels: Backend, enhancement

#24 Endpoints for tagging images from azure sdk.
  go/go.mod
  go/go.sum
  go/server/handler.go
  go/server/router.go
Labels: Azure tags, Backend

#31 Generate caption component
  client/public/uploads/iamcooldogee.jpg
  client/src/components/FileUpload.js
  client/src/components/GenerateCaption.js
  go/server/handler.go
Labels: Backend, enhancement, frontend

#36 added dockerfile
  dockerfile
Labels: Deployment

#39 split the caption into multiple lines
  client/src/components/FileUpload.js
  dockerfile
Labels: enhancement, frontend

#45 Frontend refactor and better state management
  client/package-lock.json
  client/package.json
  client/src/components/FileUpload.js
  client/src/components/GetCaption.js
  client/src/components/Progress.js
Labels: enhancement, frontend

#47 Frontend refactor
  client/src/App.js
  client/src/components/FileUpload.js
Labels: enhancement, frontend

#48 Upgraded the frontend
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/FileUpload.js
  client/src/components/GetCaption.js
  client/src/components/Progress.js
Labels: enhancement, frontend

#49 updated the readme
  README.md
Labels: documentation

#52 final readme
  README.md
Labels: documentation

#53 Frontend refactor
  client/public/index.html
  client/src/components/FileUpload.js
  client/src/components/Loading.js
Labels: enhancement, frontend

#87 Fix Network Setting
  docker-compose.yml
  go/db/db.go
Labels: Backend, bug, database

#95 Add env variable
  README.md
  web-deployment.yaml
Labels: Backend, Deployment

#99 61 fix cga
  go/db/db.go
  go/server/handler.go
Labels: Azure tags, Backend, database, urgent

#100 Filters and caption length on frontend
  client/package-lock.json
  client/package.json
  client/src/components/AllPosts.js
  client/src/components/ChooseCaption.js
  client/src/components/FileUpload.js
  client/src/components/Post.js
  go/db/db.go
  poem/Afternoon.json
Labels: enhancement, frontend
